# Generated by Django 5.1.5 on 2025-07-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=55, verbose_name='Customer Name')),
                ('cus_ph', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('booking_date', models.DateField(verbose_name='Preferred Booking Date')),
                ('booked_on', models.DateField(auto_now=True, verbose_name='Booking Created On')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.service', verbose_name='Event Type')),
            ],
        ),
    ]
